# Generated by Django 5.0.6 on 2024-06-04 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_adm', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo_disc', models.CharField(default='INF0000', max_length=7, primary_key=True, serialize=False)),
                ('nome_disc', models.CharField(max_length=7)),
                ('qtt_provas', models.PositiveSmallIntegerField(default=0)),
                ('qtt_listas', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicios',
            fields=[
                ('id_ex', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('nomearq', models.CharField(max_length=7)),
                ('arq', models.BinaryField()),
                ('data_submit', models.DateField(auto_now=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('codigo_disc', models.ForeignKey(default='INF0000', on_delete=django.db.models.deletion.CASCADE, to='finder.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Aprova',
            fields=[
                ('id_aprova', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('id_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.admin')),
                ('id_ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.exercicios')),
            ],
        ),
    ]
